### ISSUE TITLE
TypeError: create_cursor() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by nschlemm** [Polyconseil/cid#16]
as mentioned on https://docs.djangoproject.com/en/1.11/releases/1.11/#database-backend-api:
"The name keyword argument is added to the DatabaseWrapper.create_cursor(self, name=None) method to allow usage of server-side cursors on backends that support it."
(currently only postgresql)

**Comment by dbaty** [comment]
This has been fixed in ac607f33f8c3f4ca9273a618117ed3d0b629f530. A new version will be released within a week.
